apiVersion: apps/v1
kind: Deployment
metadata:
  name: arainea-frontend
  namespace: arainea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arainea-frontend
  template:
    metadata:
      labels:
        app: arainea-frontend
    spec:
      containers:
        - name: frontend
          image: cxgdn/arainea-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: VITE_API_URL
              value: "http://arainea-backend.arainea.svc.cluster.local:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: arainea-frontend
  namespace: arainea
spec:
  type: NodePort
  selector:
    app: arainea-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
